### ISSUE TITLE
[test] merge issue

### ISSUE THREAD

**Issue by jyp9533** [baepo-team/baepo-project#9]
merge하는 과정에서 생각하지 못한 이슈가 발생했습니다.
해결해보고 과정을 공유합시다!

**Comment by Scarl-ett** [comment]
제가 fork로 feature/signup 브랜치 push하면서 feature/signup 브랜치가 원격 저장소에 생성되지 않고 파일만 develop 저장소에 올라가서 이슈가 발생한 것 같습니다! push 권한 부여되어서 fork로 push한 내용 merge하기 전 브랜치로 돌려놓았습니다!

**Comment by jyp9533** [comment]
오~ 수정 감사합니다! 이따 미팅때 내용 공유해주세요!☺

**Comment by jyp9533** [comment]
오~ 수정 감사합니다! 이따 미팅때 내용 공유해주세요!☺
